/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./../src/components/AppButton.vue')['default']
    AppInput: typeof import('./../src/components/AppInput.vue')['default']
    Card: typeof import('./../src/components/Card.vue')['default']
    ContactItem: typeof import('./../src/views/contacts/components/ContactItem.vue')['default']
    CustomDevider: typeof import('./../src/views/jobs/components/CustomDevider.vue')['default']
    Header: typeof import('./../src/layouts/Header.vue')['default']
    IconEnvelope: typeof import('./../src/components/icons/IconEnvelope.vue')['default']
    IconPhone: typeof import('./../src/components/icons/IconPhone.vue')['default']
    IconPlus: typeof import('./../src/components/icons/IconPlus.vue')['default']
    JobsGrouping: typeof import('./../src/views/jobs/components/JobsGrouping.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectInput: typeof import('./../src/views/jobs/components/SelectInput.vue')['default']
  }
}
