/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./../src/components/AppButton.vue')['default']
    AppInput: typeof import('./../src/components/AppInput.vue')['default']
    Card: typeof import('./../src/components/Card.vue')['default']
    ContactItem: typeof import('./../src/views/contacts/components/ContactItem.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    IconEnvelope: typeof import('./../src/components/icons/IconEnvelope.vue')['default']
    IconPhone: typeof import('./../src/components/icons/IconPhone.vue')['default']
    IconPlus: typeof import('./../src/components/icons/IconPlus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./../src/components/Table.vue')['default']
    TableItem: typeof import('./../src/views/contacts/components/TableItem.vue')['default']
    TableView: typeof import('./../src/views/contacts/components/TableView.vue')['default']
  }
}
